/*
 * Flat config for ESLint 9. This replaces .eslintrc.js and .eslintignore, neither of
 * which ESLint 9 reads any more — without this file `yarn lint` (and therefore
 * `yarn verify`, which prepublishOnly runs) fails outright with
 * "ESLint couldn't find an eslint.config.(js|mjs|cjs) file".
 *
 * CommonJS on purpose: package.json declares no "type", so require/__dirname here
 * parse as CJS. Using ESM syntax instead would make Node reparse the file and warn
 * on every run.
 */
const { defineConfig, globalIgnores } = require('eslint/config')
const tseslint = require('@typescript-eslint/eslint-plugin')
const tsParser = require('@typescript-eslint/parser')
const prettier = require('eslint-config-prettier/flat')
const globals = require('globals')
const importPlugin = require('eslint-plugin-import')
const jsdoc = require('eslint-plugin-jsdoc')
const preferArrow = require('eslint-plugin-prefer-arrow')
const react = require('eslint-plugin-react')

module.exports = defineConfig([
  // Ported from .eslintignore plus the old `ignorePatterns`. Directory patterns need
  // the /** suffix and nested matches need the **/ prefix — a bare '*.test.ts' matches
  // nothing below the root. node_modules and .git are ignored by default.
  globalIgnores([
    'lib/**', // build output (tsconfig outDir)
    'example/**', // self-contained Expo app with its own package.json and tsconfig
    'scripts/**', // plain CommonJS node scripts, in no tsconfig
    'web-build/**', // generated by predeploy
    'coverage/**',
    '.expo/**',
    '**/*.config.js', // babel / metro / react-native configs
    '**/*.test.ts',
    '**/*.test.tsx',
  ]),

  {
    // Scoped to exactly what tsconfig.json includes (["src", "App.tsx", "./typings.d.ts"]).
    // This is load-bearing: the type-checked preset's own config objects carry no `files`
    // key, so left unscoped they would apply type-aware rules to plain .js files that have
    // no program behind them, which is a hard error rather than a lint finding.
    files: ['src/**/*.{ts,tsx}', 'App.tsx', 'typings.d.ts'],

    // Mirrors the old extends order. prettier belongs here rather than in a later
    // top-level entry so that the local rules block below still overrides it, which is
    // what the eslintrc did.
    extends: [
      tseslint.configs['flat/recommended'],
      tseslint.configs['flat/recommended-type-checked'],
      prettier,
    ],

    // Required: the rules block sets jsdoc/* and prefer-arrow/* at 'error', so these
    // plugins have to be registered or config resolution fails. eslint-plugin-import is
    // registered by hand rather than via its flatConfigs preset — the preset registers a
    // different object than the module export, and using both throws "Cannot redefine
    // plugin".
    plugins: {
      import: importPlugin,
      jsdoc,
      'prefer-arrow': preferArrow,
      react,
    },

    languageOptions: {
      parser: tsParser,
      parserOptions: {
        project: true,
        tsconfigRootDir: __dirname,
        sourceType: 'module',
      },
      globals: { ...globals.browser }, // replaces the old env: { browser: true }
    },

    settings: { react: { version: 'detect' } },

    // Carried over unchanged, minus six `@typescript-eslint` formatting rules that no
    // longer exist in v8 (indent, quotes, semi, member-delimiter-style,
    // type-annotation-spacing, no-parameter-properties). They were all set to 'off', which
    // ESLint tolerates for unknown rules, but turning any of them back on would crash.
    // Note '@typescript-eslint/no-empty-interface' below is deprecated upstream in favour
    // of no-empty-object-type, which flat/recommended already enables.
    rules: {
      '@typescript-eslint/unbound-method': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/adjacent-overload-signatures': 'error',
      '@typescript-eslint/array-type': [
        'error',
        {
          default: 'array',
        },
      ],
      '@typescript-eslint/no-restricted-types': [
        'error',
        {
          types: {
            Object: {
              message: 'Avoid using the `Object` type. Did you mean `object`?',
              suggest: ['object'],
            },
            Function: {
              message:
                'Avoid using the `Function` type. Prefer a specific function type, like `() => void`.',
            },
            Boolean: {
              message:
                'Avoid using the `Boolean` type. Did you mean `boolean`?',
              suggest: ['boolean'],
            },
            Number: {
              message: 'Avoid using the `Number` type. Did you mean `number`?',
              suggest: ['number'],
            },
            String: {
              message: 'Avoid using the `String` type. Did you mean `string`?',
              suggest: ['string'],
            },
            Symbol: {
              message: 'Avoid using the `Symbol` type. Did you mean `symbol`?',
              suggest: ['symbol'],
            },
          },
        },
      ],
      '@typescript-eslint/consistent-type-assertions': 'error',
      '@typescript-eslint/dot-notation': 'off',
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/explicit-member-accessibility': [
        'off',
        {
          accessibility: 'explicit',
        },
      ],
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      '@typescript-eslint/naming-convention': [
        'off',
        {
          selector: 'variable',
          format: ['camelCase', 'UPPER_CASE'],
          leadingUnderscore: 'forbid',
          trailingUnderscore: 'forbid',
        },
      ],
      '@typescript-eslint/no-empty-function': 'off',
      '@typescript-eslint/no-empty-interface': 'error',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-misused-new': 'error',
      '@typescript-eslint/no-namespace': 'error',
      '@typescript-eslint/no-shadow': [
        'off',
        {
          hoist: 'all',
        },
      ],
      '@typescript-eslint/no-unused-expressions': 'error',
      '@typescript-eslint/no-use-before-define': 'off',
      // Replaces the eslintrc's '@typescript-eslint/no-var-requires': 'off'. That
      // rule is deprecated since v8 in favour of no-require-imports, which
      // flat/recommended enables — so the original intent (require() is allowed) was
      // being lost. Narrowed to image assets: require() is how React Native resolves
      // platform-suffixed images, and there is no static-import equivalent without
      // declaring the asset modules.
      '@typescript-eslint/no-require-imports': ['error', { allow: ['\\.png$'] }],
      '@typescript-eslint/prefer-for-of': 'error',
      '@typescript-eslint/prefer-function-type': 'error',
      '@typescript-eslint/prefer-namespace-keyword': 'error',
      '@typescript-eslint/triple-slash-reference': [
        'error',
        {
          path: 'always',
          types: 'prefer-import',
          lib: 'always',
        },
      ],
      '@typescript-eslint/typedef': 'off',
      '@typescript-eslint/unified-signatures': 'error',
      'arrow-parens': ['off', 'always'],
      'brace-style': ['off', 'off'],
      'comma-dangle': 'off',
      complexity: 'off',
      'constructor-super': 'error',
      'dot-notation': 'off',
      'eol-last': 'off',
      eqeqeq: ['error', 'smart'],
      'guard-for-in': 'error',
      'id-denylist': 'off',
      'id-match': 'off',
      'import/order': [
        'off',
        {
          alphabetize: {
            caseInsensitive: true,
            order: 'asc',
          },
          'newlines-between': 'ignore',
          groups: [
            ['builtin', 'external', 'internal', 'unknown', 'object', 'type'],
            'parent',
            ['sibling', 'index'],
          ],
          distinctGroup: false,
          pathGroupsExcludedImportTypes: [],
          pathGroups: [
            {
              pattern: './',
              patternOptions: {
                nocomment: true,
                dot: true,
              },
              group: 'sibling',
              position: 'before',
            },
            {
              pattern: '.',
              patternOptions: {
                nocomment: true,
                dot: true,
              },
              group: 'sibling',
              position: 'before',
            },
            {
              pattern: '..',
              patternOptions: {
                nocomment: true,
                dot: true,
              },
              group: 'parent',
              position: 'before',
            },
            {
              pattern: '../',
              patternOptions: {
                nocomment: true,
                dot: true,
              },
              group: 'parent',
              position: 'before',
            },
          ],
        },
      ],
      indent: 'off',
      'jsdoc/check-alignment': 'error',
      'jsdoc/check-indentation': 'error',
      'linebreak-style': 'off',
      'max-classes-per-file': ['error', 1],
      'max-len': 'off',
      'new-parens': 'off',
      'newline-per-chained-call': 'off',
      'no-bitwise': 'error',
      'no-caller': 'error',
      'no-cond-assign': 'error',
      'no-console': 'off',
      'no-debugger': 'error',
      'no-empty': 'off',
      'no-empty-function': 'off',
      'no-eval': 'error',
      'no-extra-semi': 'off',
      'no-fallthrough': 'off',
      'no-invalid-this': 'off',
      'no-irregular-whitespace': 'off',
      'no-multiple-empty-lines': 'off',
      'no-new-wrappers': 'error',
      'no-shadow': 'off',
      'no-throw-literal': 'error',
      'no-trailing-spaces': 'off',
      'no-undef-init': 'error',
      'no-underscore-dangle': 'off',
      'no-unsafe-finally': 'error',
      'no-unused-expressions': 'off',
      'no-unused-labels': 'error',
      'no-use-before-define': 'off',
      'no-var': 'error',
      'object-shorthand': 'error',
      'one-var': ['off', 'never'],
      'padded-blocks': [
        'off',
        {
          blocks: 'never',
        },
        {
          allowSingleLineBlocks: true,
        },
      ],
      'prefer-arrow/prefer-arrow-functions': 'error',
      'prefer-const': 'error',
      'quote-props': 'off',
      quotes: 'off',
      radix: 'error',
      'react/jsx-curly-spacing': 'off',
      'react/jsx-equals-spacing': 'off',
      'react/jsx-tag-spacing': [
        'off',
        {
          afterOpening: 'allow',
          closingSlash: 'allow',
        },
      ],
      'react/jsx-wrap-multilines': 'off',
      semi: 'off',
      'space-before-function-paren': 'off',
      'space-in-parens': ['off', 'never'],
      'spaced-comment': [
        'error',
        'always',
        {
          markers: ['/'],
        },
      ],
      'use-isnan': 'error',
      'valid-typeof': 'off',
    },
  },
])
